name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_version: ['25', '26', '27']
        elixir_version: ['1.15', '1.16', '1.17', '1.18']
        exclude:
        - otp_version: '27'
          elixir_version: '1.15'
        - otp_version: '27'
          elixir_version: '1.16'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir_version }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp_version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp_version }}-mix-
    - name: Install compression utilities
      run: sudo apt install brotli zstd
    - name: Install dependencies
      run: mix do deps.get, deps.compile
    - name: Run tests
      run: mix test
